import java.util.Scanner;

public class NomeCompleto {

    /*Crie um programa Java que declare duas variáveis do tipo String para armazenar o primeiro nome e o sobrenome de uma pessoa.
     Em seguida, concatene essas duas strings para formar o nome completo e exiba-o na tela. */

    public static void main(String[] args) {

        // Declara as variáveis para o nome e sobrenome
        String nome = "Alex";
        String sobrenome = "Alves";

        // Declara as strings para formar o nome completo
        String nomeCompleto = nome + " " + sobrenome;

        // Exibe o nome completo na tela
        System.out.println("Nome Completo: " + nomeCompleto);
    }
}

/*Neste programa, declarasse duas variáveis 'String​'​ chamadas 'Nome' e 'sobrenome'.
'+'parágrafo j 'System.out.println' para exibir o 'Nome' 'sobrenome' pelos nomes que desejar */